### ISSUE TITLE
Caching Strategy Not Effective with 1000+ Redirects

### ISSUE THREAD

**Issue by tlovett1** [10up/safe-redirect-manager#24]
I was using the plugin today on a huge site. We wanted to insert 11,000+ redirects. This resulted an exceeded memory limit fatal error.

The plugin caches all the published redirects in a transient. Then on each page request, the current page is checked against every redirect in the transient. This results in worst case performance O( n ). I think we can definitely do this better.

**Comment by mehul0810** [comment]
Adding my thoughts to improve the overall performance of the plugin with thousands of redirects:

### Recommendations
1. **Storing data in a custom table:** This will drastically improve the performance of CRUD operations.
2. **Adding an index:** This will improve performance for the repeated queries.
3. **More control:** We can create our own SQL queries by creating our own class to manage CRUD operations that will make them more robust and scalable.

### Challenges
- Initial development efforts are required to implement this feature
- Ensuring that the upgrade routine will smoothly transfer the large chunk of data inside a single transient safely into a custom table

I hope this information will be useful.

**Comment by Sidsector9** [comment]
Since PHP arrays are implemented using hash tables, what if we save redirects with a key before saving to the transient?

Currently we do this:
```php
$redirects[] = array(
	'ID'            => $redirect_id,
	'post_status'   => get_post_status( $redirect_id ),
	'redirect_from' => get_post_meta( $redirect_id, '_redirect_rule_from', true ),
	'redirect_to'   => get_post_meta( $redirect_id, '_redirect_rule_to', true ),
	'status_code'   => (int) get_post_meta( $redirect_id, '_redirect_rule_status_code', true ),
	'enable_regex'  => (bool) get_post_meta( $redirect_id, '_redirect_rule_from_regex', true ),
);

```

We can modify it to:
```php
$redirect_from = get_post_meta( $redirect_id, '_redirect_rule_from', true );

$redirects[ $redirect_from ] = array( // Add value of `redirect_from` meta as key.
	'ID'            => $redirect_id,
	'post_status'   => get_post_status( $redirect_id ),
	'redirect_from' => $redirect_from,
	'redirect_to'   => get_post_meta( $redirect_id, '_redirect_rule_to', true ),
	'status_code'   => (int) get_post_meta( $redirect_id, '_redirect_rule_status_code', true ),
	'enable_regex'  => (bool) get_post_meta( $redirect_id, '_redirect_rule_from_regex', true ),
);
```

Instead of running a `foreach` [here](https://github.com/10up/safe-redirect-manager/blob/develop/inc/classes/class-srm-redirect.php#L127), we can lookup for `isset( $redirects[ $to_match ] )`. This will take `O(1)`.

This approach assumes that there cannot be multiple redirects with the same "redirect_from" value. (Something that I was able to do otherwise from the WP backend.)

If this looks reasonable and we go ahead, the next update of the plugin would require an upgrade script that rebuilds any existing cache with the new structure.

**Comment by jeffpaul** [comment]
@tlovett1 @pdclark @mehul0810 any feedback on @Sidsector9's recommendation above?

**Comment by pdclark** [comment]
It's been a while! Custom table makes most sense to me. I don't know that adding keys in PHP would help much in case of regexes.

**Comment by mehul0810** [comment]
The recommendation by @Sidsector9 is helpful to achieve a minor performance boost. But, as the main issue is focused on the large sites having thousands of redirects, the pain point here is fetching a large chunk of data from a single transient. 

So, considering the huge site with a large chunk of data and for VIP the `wp_options` to be < `1M`, then my recommendation will still be custom tables for a significant performance boost.

**Comment by jeffpaul** [comment]
@dkotter any thoughts on best approach here?

**Comment by dkotter** [comment]
Reading through the ideas that have been floated in this thread, here are my thoughts:

The overall structure of the plugin has changed a lot since [this comment](https://github.com/10up/safe-redirect-manager/issues/24#issuecomment-55110810) was added in 2014 so some of the steps mentioned here will no longer work. I think the overall idea though was to reduce the amount of data we are storing. I think that is still a viable solution and would be easy to implement, does mean we would be running new queries once a match is found or if wildcards are used (to get the `redirect_to` value). Would be interesting to run some tests to see how that impacts performance.

The [idea](https://github.com/10up/safe-redirect-manager/issues/24#issuecomment-939931196) of a custom table probably would help the most, though in the original reported issue of 11,000+ redirects, I would imagine pulling those from a custom table could still have performance problems. The current approach of caching this data is to ensure we're not running multiple queries on the database for every single page load. If I'm understanding this recommended approach correctly, we would switch from not caching data at all and just pull data from a custom table on each request. I would be interested to know how that would impact performance, especially once we get to multiple thousands of redirects.

Ultimately I'm not sure this plugin is the best choice in those situations. If you truly need that many redirects, seems like there's better options to handle those (preferably at the server-level or if in the case of WP VIP, they have options to do this at the `wp-config.php` level). Not saying that doesn't mean we should look to help with performance but we do need to weigh the amount of effort it would take to build a new data structure and migrate all existing content to that structure if the great majority of users aren't experiencing performance problems.

I would love to see next steps here of putting together a test environment that has thousands of redirects and try making some smaller tweaks to see how much that can help (more in line with the first approach I mention here). That could provide enough of an improvement that we don't need to go the route of a full data structure change.

**Comment by noraconley** [comment]
I created a [testing branch](https://github.com/10up/safe-redirect-manager/tree/testing/create-test-redirects) that adds two new commands for creating test rules: `wp safe-redirect-manager create-test <num-of-redirects-to-create>` and `wp safe-redirect-manager delete-test` (deletes all rules that were created with the `create-test` command).

Please note that the `create-test` command is very slow, as it uses `wp_insert_post` and attempts to create a variety of rules. This should only be used for testing the approach here.

Next steps would be to establish some base lines and test against the smaller fixes mentioned previously.

**Comment by noraconley** [comment]
I did some testing and research on this issue. I performed my testing with **10,000** redirect rules.

My steps for setting up a base:

1. Delete all previous redirects.
1. Create 10,000 redirect rules: `wp safe-redirect-manager create-test` 10000 (this will take a while; 30-60 minutes) [test branch here](https://github.com/10up/safe-redirect-manager/tree/testing/create-test-redirects) 
1. `return;` right before `wp_safe_redirect` in `SRM_Redirect->maybe_redirect();`
1. Set `ini_set( ‘memory_limit’, ‘512M’ );`. I did this in `wp-config.php`.
1. Add a filter:  `add_filter( 'srm_max_redirects', function() {
    return 10001;
} );`
1. I hit the last redirect rule in the transient: `/10000-from/test`

## Testing methodology

I used Query Monitor and averaged 10 results. The stats are as follows:

1. Page generation time in seconds
1. Peak memory usage
1. Total time taken by SQL queries in seconds
1. Total number of SQL queries

## I considered three main points of optimization

### 1. The request that builds the transient.

To test the uncached page, run:  `wp safe-redirect-manager update-cache` or modify `srm_redirects( array(), true )` in `SRM_Redirect->match_redirect();`

I believe I have found a way to cut the number of queries in half. The transient includes a call to `get_post_status()`, which does not seem to be used anywhere. This requires an extra query for every redirect rule. Removing this reduced the number of queries from 20,239 to 10,239.

I also tested join statements.  I found that 1000 per page was the only way to increase numbers using JOIN. I ensured unique test results by incrementing `WHERE 1=1` for each test.

JOIN with all meta:
```php
$redirect_results = $wpdb->get_results(
	$wpdb->prepare(
		"SELECT posts.ID, redirect_from.meta_value AS redirect_from, redirect_regex.meta_value AS enable_regex, redirect_to.meta_value AS redirect_to, redirect_status.meta_value AS status_code
		FROM $wpdb->posts AS posts
		INNER JOIN $wpdb->postmeta AS redirect_from
			ON posts.ID = redirect_from.post_id
			AND redirect_from.meta_key = '_redirect_rule_from'
		INNER JOIN $wpdb->postmeta AS redirect_regex
			ON posts.ID = redirect_regex.post_id
			AND redirect_regex.meta_key = '_redirect_rule_from_regex'
		INNER JOIN $wpdb->postmeta AS redirect_to
			ON posts.ID = redirect_to.post_id
			AND redirect_to.meta_key = '_redirect_rule_to'
		INNER JOIN $wpdb->postmeta AS redirect_status
			ON posts.ID = redirect_status.post_id
			AND redirect_status.meta_key = '_redirect_rule_status_code'
		WHERE 1=1
		AND posts.post_type = 'redirect_rule'
		AND ((posts.post_status = 'publish'))
		ORDER BY posts.menu_order ASC, posts.ID ASC
		LIMIT %d, 1000",
		( $i - 1 ) * 1000
	)
);
```

JOIN with only regex and from:
```php
$redirect_results = $wpdb->get_results(
	$wpdb->prepare(
		"SELECT posts.ID, redirect_from.meta_value AS redirect_from, redirect_regex.meta_value AS enable_regex
		FROM $wpdb->posts AS posts
		INNER JOIN $wpdb->postmeta AS redirect_from
			ON posts.ID = redirect_from.post_id
			AND redirect_from.meta_key = '_redirect_rule_from'
		INNER JOIN $wpdb->postmeta AS redirect_regex
			ON posts.ID = redirect_regex.post_id
			AND redirect_regex.meta_key = '_redirect_rule_from_regex'
		WHERE 1=1
		AND posts.post_type = 'redirect_rule'
		AND ((posts.post_status = 'publish'))
		ORDER BY posts.menu_order ASC, posts.ID ASC
		LIMIT %d, 1000",
		( $i - 1 ) * 1000
	)
);
```

**Base:**

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 2.8s | 285.4 MB | 1.37s | 20,239 |

**Removing `get_post_status()`:**

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 1.4s | 144.5 MB | 0.631s | 10,239 |

**Removing `get_post_status()`; 1000 per page:** 

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 1.414s | 148.3 MB | 0.643s | 10,060 |

**JOIN all post meta; 1000 per page:**

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 1.091s | 16.8 MB | 0.868s | 49 |

**JOIN only `_redirect_rule_from` and `_redirect_rule_from_regex`; 1000 per page:** 

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 0.782s | 22.3 MB | 0.561s | 50 |

**Additional Ideas:**
1. Use a primed cache approach
1. Investigate using an alternate serializing function.

### 2. The size of the transient.

In my test, the size of the serialized array in the transient is ~1.87 MB. This does not account for longer possible “from” and “to” that could greatly inflate this number.

**Testing size of transient value:**
1. Base: **1.87 MB**
1. Removing `post_status` key: **1.54 MB**
1. Storing all results, without a named key (no `post_status`): **860 KB**
1. Storing only ID, from, and regex: **991 KB**
1. Storing only ID, from, and regex, without a named key: **571 KB**

### 3. A request that reads the transient and tests for a match

I have some additional ideas below.

**Base results:** 

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 0.22s | 15.6 MB | 0.005s | 35 |

**No post status:** 

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 0.205s | 14.2 MB | 0s | 35 |

**Only storing ID, regex, and from; no post status; look up “to” and status code on load:** 

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 0.201s | 12.1 MB | 0s | 36 |

**Only storing ID, regex, and from; no post status; no array keys; look up “to” and status code on load:** 

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 0.201s | 11 MB | 0.001s | 36 |

**[Very experimental] Storing the “from” as the key of an array; hitting an endpoint that I know does not have a wildcard or regex; using `isset()`; `array( '/from-rule' => 123 )`;**

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 0.187s | 6.3 MB | 0s | 36 |

**Additional Ideas:**
1. Investigate using an alternate serializing function.
1. Separate transients for non-regex/non-wildcard from rules and regex from rules. As mentioned previously, we could can use `isset()` for the non-regex/non-wildcard transient.

**Comment by dkotter** [comment]
@nateconley Sorry for the very late reply here but curious if you have a summary of the above as far as what you would suggest for next steps?

I will say I'm surprised that with 10,000 redirects, performance isn't worse. 2.8s page generation time and 285 MB memory usage isn't too horrible. It seems like a very easy answer is removing the use of `get_post_status` (assuming that isn't needed), as that seems to reduce numbers by half across the board.

But beyond that obvious change, are there other things you'd suggest we look to do?

**Comment by noraconley** [comment]
@dkotter In my opinion, the only other worthwhile optimization that I uncovered would be the `JOIN` statements (as opposed to gathering meta for each individual redirect), but this could easily _decrease_ performance for users with less than 1000 redirects.
